<a href="https://colab.research.google.com/github/Pradhima-9/dl/blob/main/dlex8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

samples = {'Jupiter has 79 known moons.', 'Neptune has 14 confirmed moons!'}
token_index = {}
counter = 0

# Build the token index
for sample in samples:
    for considered_word in sample.split():
        if considered_word not in token_index:
            token_index.update({considered_word: counter + 1})
            counter = counter + 1

print(token_index)
# Expected output: {'Jupiter': 1, 'has': 2, '79': 3, 'known': 4, 'moons.': 5, 'Neptune': 6, '14': 7, 'confirmed': 8, 'moons!': 9}

# Create the one-hot encoded representation
max_length = 6  # Maximum length of a sentence
results = np.zeros(shape=(len(samples), max_length, max(token_index.values()) + 1))

for i, sample in enumerate(samples):
    for j, considered_word in list(enumerate(sample.split())):
        index = token_index.get(considered_word)

        # Check if the word is in token_index and if j is within the bounds of max_length
        if index is not None and j < max_length:
            results[i, j, index] = 1.

print(results) # Print the one-hot encoded results

{'Neptune': 1, 'has': 2, '14': 3, 'confirmed': 4, 'moons!': 5, 'Jupiter': 6, '79': 7, 'known': 8, 'moons.': 9}
[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
